version: '3.4'

services:
  recall-zipkin:
    ports:
      - "35411:9411"  
  
  
  recall-sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "35433:1433"
    volumes:
      - recall-sqldata:/var/opt/mssql  
      
  recall-seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "35340:80"      
        
  recall-textitemapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "35210:8080"
      - "50001"
    
        
  recall-textitemapi-dapr:
    command: ["./daprd",
              "-app-id", "recall-textitemapi",
              "-app-port", "8080",
              "-components-path", "/components",
              "-config", "/configuration/recall-configuration.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    
  servicestatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
volumes:
  recall-sqldata:
    external: false
